version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: cd FrontEnd/agme && npm install
      - run: cd FrontEnd/agme && npm test
  build-backend:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: 
          key: circleci-demo-java-spring-{{ checksum "BackEnd/agme/pom.xml" }}
      - run: cd BackEnd/agme && mvn dependency:go-offline 
      - save_cache:
          paths:
              - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "BackEnd/agme/pom.xml" }}
      - run: cd BackEnd/agme &&  mvn package 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-frontend
      - build-backend